# Generated by Django 4.1 on 2023-01-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blogpost_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.media'),
        ),
        migrations.AlterField(
            model_name='media',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
    ]
